import gradio as gr
from askbio import AskBio  # Assuming your chatbot class is in a file named askbio.py

# Initialize the AskBio object
askbio = AskBio()


def chat_with_askbio(message, history=None):
    """
    Function to handle interaction with the AskBio chatbot.
    
    Args:
    user_input (str): The question asked by the user.
    
    Returns:
    str: The response generated by AskBio.
    """
    if not message.strip():
        return "Please enter a valid question."
    
    try:
        # Get the response from AskBio based on user's input message
        response = askbio.ask(message)
        return response
    except Exception as e:
        return f"An error occurred while processing your question: {str(e)}"


# Create the Gradio interface
iface = gr.ChatInterface(chat_with_askbio,
                         chatbot=gr.Chatbot(height=700),
                         textbox=gr.Textbox(placeholder="Enter your question here...", container=False, scale=7),
                         title="AskBio", 
                         description="AskBio is a chatbot specialized in biology. Type your questions and get instant responses!",)

# Run the Gradio app
if __name__ == "__main__":
    iface.launch()
